// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiThiNVT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230629020325_Create_Table_NVTCau3")]
    partial class Create_Table_NVTCau3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("BaiThiNVT.Models.NVTCau3", b =>
                {
                    b.Property<string>("IDNhanVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TuoiNhanVien")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDNhanVien");

                    b.ToTable("NVTCau3");
                });
#pragma warning restore 612, 618
        }
    }
}
